services:
  api:
    container_name: fasealterna-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    restart: unless-stopped
    networks:
      - fasealterna-backend-dev

networks:
  fasealterna-backend-dev:
    driver: bridge
